### PR TITLE
modulesync 4.0.0

### PR DESCRIPTION
**Pull request by bastelfreak**
modulesync 4.0.0

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
Ubuntu with Puppet 5 failures are expected, but Fedora 26 is EOL. That should be updated to a current Fedora version.

**Review by ekohl — APPROVED** [review]

**Review by ekohl — CHANGES_REQUESTED** [review]
Looks like Fedora 32 fails.

**Review by ekohl — CHANGES_REQUESTED** [review]
Please also drop https://github.com/voxpupuli/puppet-ferm/blob/fb8ed26cdceb012c3395a8d897b98785b17f087f/manifests/install.pp#L47-L53. That probably also means you should drop `$manage_initfile`.

**Comment by bastelfreak** [comment]
@ekohl updated it

**Review by ekohl — APPROVED** [review]

**Pull request merged**
